"""datetime

Revision ID: 14912a8644ca
Revises: e87727e845eb
Create Date: 2025-11-25 17:49:49.392788

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14912a8644ca'
down_revision: str | None = 'e87727e845eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('date_time', sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###
